Import('env')

env['LIBS'] = ['sfml-audio.lib', 'sfml-graphics.lib', 'sfml-network.lib', 'sfml-system.lib', 'sfml-window.lib']

srcFiles = Glob('*.cpp')

if not GetOption('projects'):
  env.Program('Game', source=srcFiles)

Return('srcFiles')